小池百合子流
suuei/cooking pull request #1
Opened 2021-03-18 13:54 UTC by marukaz

2021-03-18 14:13 UTC, suuei requested changes
(両方とも俺のミスじゃねえか‼️)

2021-03-18 14:13 UTC, suuei commented on README.md
>  ## 材料(2人分)
- Heading styleを統一してほしいです (`##`ではなく`----`)
- 末尾の空白を削除してください

2021-03-18 14:13 UTC, suuei commented on README.md
> +*あとは、踊るだけ。*
最後に改行を入れてください

2021-03-18 15:01 UTC, marukaz commented
密です

2021-03-19 12:27 UTC, merged

2021-03-19 12:27 UTC, suuei commented
優勝👆